### ISSUE TITLE
'waf update' fails with AttributeError: 'module' object has no attribute 'download_tool'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [waf-project/waf#1541]
```
>> operating system:
OS X Yosemite

>> python version:
Python 2.7.8

>> waf version (or git revision):
1.8.7

>> observed output and expected output:

➜  c++-casablanca git:(master) ✗ wget 
http://ftp.waf.io/pub/release/waf-1.8.7
--2015-03-02 13:40:25--  http://ftp.waf.io/pub/release/waf-1.8.7
Resolving ftp.waf.io... 140.211.9.20
Connecting to ftp.waf.io|140.211.9.20|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 96856 (95K) [text/plain]
Saving to: 'waf-1.8.7'

waf-1.8.7                                                           
100%[===========================================================================
================================================================================
==========>]  94.59K  96.8KB/s   in 1.0s

2015-03-02 13:40:26 (96.8 KB/s) - 'waf-1.8.7' saved [96856/96856]

➜  c++-casablanca git:(master) ✗ mv waf-1.8.7 waf
➜  c++-casablanca git:(master) ✗ chmod +x waf
➜  c++-casablanca git:(master) ✗ ./waf update --files=boost
Traceback (most recent call last):
  File "/Users/wotte/Desktop/destiny/c++-casablanca/.waf-1.8.7-e6b2961ae4a2b8021fcc5c4bba50704b/waflib/Scripting.py", line 103, in waf_entry_point
    run_commands()
  File "/Users/wotte/Desktop/destiny/c++-casablanca/.waf-1.8.7-e6b2961ae4a2b8021fcc5c4bba50704b/waflib/Scripting.py", line 164, in run_commands
    ctx=run_command(cmd_name)
  File "/Users/wotte/Desktop/destiny/c++-casablanca/.waf-1.8.7-e6b2961ae4a2b8021fcc5c4bba50704b/waflib/Scripting.py", line 155, in run_command
    ctx.execute()
  File "/Users/wotte/Desktop/destiny/c++-casablanca/.waf-1.8.7-e6b2961ae4a2b8021fcc5c4bba50704b/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/Users/wotte/Desktop/destiny/c++-casablanca/.waf-1.8.7-e6b2961ae4a2b8021fcc5c4bba50704b/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/Users/wotte/Desktop/destiny/c++-casablanca/.waf-1.8.7-e6b2961ae4a2b8021fcc5c4bba50704b/waflib/Scripting.py", line 360, in update
    Configure.download_tool(tool,force=True,ctx=ctx)
AttributeError: 'module' object has no attribute 'download_tool'

>> how to reproduce the problem?

Above

>> testcase - how to reproduce? (provide attachments for testcase files)

Above
```

Original issue reported on code.google.com by `will.o...@gmail.com` on 2 Mar 2015 at 7:44

**Comment by ita1024** [comment]
Proper error message added in 991ec81510fc77efecd429a0105d04aeea2481c0
