### ISSUE TITLE
waflib/extras/why.py is broken

### ISSUE THREAD

**Issue by Rob3rtS** [waf-project/waf#1561]
It seems, since commit 1551b070 waflib/extras/why.py does not work anymore.

With commit 31f399e6:
waf build --zones=task
...
Build failed
Traceback (most recent call last):
  File ".../waf/waflib/Runner.py", line 287, in task_status
    return tsk.runnable_status()
  File ".../waf/waflib/extras/why.py", line 54, in runnable_status
    ret = old(self)
  File ".../waf/waflib/Task.py", line 590, in runnable_status
    new_sig = self.signature()
  File ".../waf/waflib/extras/why.py", line 24, in signature
    self.m.update(self.hcode.encode())
AttributeError: 'bytes' object has no attribute 'encode'

Please see my fix: https://github.com/Rob3rtS/attachments-pool/blob/master/0001-fixed-why.py.patch

**Comment by ita1024** [comment]
Pull requests are easier to merge.

r3e3c84abfb4f0fb005c6a00f5eed72bf9552110d
