### ISSUE TITLE
unstable on waf/demo/c

### ISSUE THREAD

**Issue by hanbeibei** [waf-project/waf#1592]
Hi,

I'm new user of waf, here is some problem which happened when I try to configure the waf/demo/c, the status is not stable, 

here is the command sequence which I did:
waf configure build
waf clean
waf distclean
waf configure

and got the following log on the screen.

$ waf configure
Setting top to                           : c:\software\waf-1.8.11.1\waf-1.8.11\d
emos\c
Setting out to                           : c:\software\waf-1.8.11.1\waf-1.8.11\d
emos\c\build
Checking for 'msvc' (C compiler)         : not found
Checking for 'gcc' (C compiler)          : c:\Anaconda3\Scripts\gcc.bat
Checking for code snippet                : yes
Checking for code snippet                : yes
Checking for code snippet                : yes
Checking for libraries                   : Traceback (most recent call last):
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Scripting.py", line 108, in waf_entry_point
    run_commands()
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Scripting.py", line 169, in run_commands
    ctx=run_command(cmd_name)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Scripting.py", line 160, in run_command
    ctx.execute()
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Configure.py", line 92, in execute
    super(ConfigurationContext,self).execute()
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Context.py", line 133, in recurse
    user_function(self)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\demos\c\wscript", line 31, in config
ure
    conf.check_library(test_exec=True)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Configure.py", line 189, in fun
    return f(*k,**kw)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Tools\c_tests.py", line 51, in check_library
    self.check(compile_filename=[],features='link_lib_test',msg='Checking for li
braries',mode=mode,test_exec=test_exec,)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Configure.py", line 189, in fun
    return f(*k,**kw)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Tools\c_config.py", line 412, in check
    ret=self.run_build(*k,**kw)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Configure.py", line 189, in fun
    return f(*k,**kw)
  File "c:\software\waf-1.8.11.1\waf-1.8.11\waf3-1.8.11-ec34a0d79a17688c838f1564
bf01c5fd\waflib\Configure.py", line 351, in run_build
    shutil.rmtree(dir)
  File "c:\Anaconda3\lib\shutil.py", line 477, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\Anaconda3\lib\shutil.py", line 367, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\Anaconda3\lib\shutil.py", line 372, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\Anaconda3\lib\shutil.py", line 370, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'c:\\software\\waf-1.8.11.1\\waf
-1.8.11\\demos\\c\\build\\conf_check_e220321d294f6a38df5c81725b51d76d\\testbuild
\\app.exe'

**Comment by hanbeibei** [comment]
I mentional this because sometimes it works.

after I run: waf configure, I got build folder on the directory

**Comment by ita1024** [comment]
Disable your antivirus. Files being scanned cannot be removed.
