### ISSUE TITLE
Book: Error in "Searching and creating nodes" example

### ISSUE THREAD

**Issue by termim** [waf-project/waf#1617]
I'm trying some examples from the book and get the following error for the
 "Searching and creating nodes" example:

 :/tmp>waf --version
waf --version
waf 1.8.12 (ae508f2f82fbfad4420f7920b6f68a6801e383fd)

 :/tmp>waf distclean configure dosomething
Compilation started at Mon Aug 31 16:06:27

waf distclean configure dosomething
'distclean' finished successfully (0.001s)
Setting top to                           : /tmp
Setting out to                           : /tmp/build
'configure' finished successfully (0.002s)
wscript
foo.txt
Traceback (most recent call last):
  File "/usr/share/waf/waflib/Scripting.py", line 107, in waf_entry_point
    run_commands()
  File "/usr/share/waf/waflib/Scripting.py", line 168, in run_commands
    ctx=run_command(cmd_name)
  File "/usr/share/waf/waflib/Scripting.py", line 159, in run_command
    ctx.execute()
  File "/usr/share/waf/waflib/Context.py", line 91, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/usr/share/waf/waflib/Context.py", line 132, in recurse
    user_function(self)
  File "/tmp/wscript", line 10, in dosomething
    nd2 = ctx.path.search('foo.txt')
AttributeError: 'Nod3' object has no attribute 'search'

**Comment by ita1024** [comment]
Yes, it is called search_node not search

**Comment by ita1024** [comment]
Fixed.
