### ISSUE TITLE
`Utils.subs_vars` fails for unknown reason

### ISSUE THREAD

**Issue by drahnr** [waf-project/waf#1639]
```
Build failed
Traceback (most recent call last):
  File "/home/tom/projects/oregano/.waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57/waflib/Task.py", line 110, in process
    ret=self.run()
  File "/home/tom/projects/oregano/.waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57/waflib/Build.py", line 455, in run
    return self.generator.exec_task()
  File "/home/tom/projects/oregano/.waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57/waflib/Build.py", line 463, in exec_install_files
    destpath=self.get_install_path()
  File "/home/tom/projects/oregano/.waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57/waflib/Build.py", line 457, in get_install_path
    dest=Utils.subst_vars(self.dest,self.env)
  File "/home/tom/projects/oregano/.waf-1.8.14-7d91ad6f638c7699369d1dae6bcada57/waflib/Utils.py", line 336, in subst_vars
    return reg_subst.sub(repl_var,expr)
TypeError: expected string or buffer
```

`wscript`:
https://github.com/drahnr/oregano/blob/wip-deprecation-refactor/wscript

`ci`-results:
waf = 1.8.14
http://drone.ahoi.io/github.com/drahnr/oregano/wip-deprecation-refactor/4a05cf4832992f94ee858c2ec8495505c1ec8029
and
waf = 1.8.13
http://drone.ahoi.io/github.com/drahnr/oregano/wip-deprecation-refactor/628b6dcd7694a9392a75abc27a38d498ac6e0266

I'd be more than happy to understand why and where it fails.

A similar issue arose also here, but no valuable explanation/solution was provided https://github.com/brainfucker/hashlib/issues/1

**Comment by ita1024** [comment]
We can add an assertion, but `bld.install_files(None, 'wscript')` is still invalid.

**Comment by ita1024** [comment]
0357db515646732e7ec301e9551f77b8c5afc03f

**Comment by drahnr** [comment]
@ita1024 sweet deal, thank you!
