### ISSUE TITLE
Decoding issues in Context.py

### ISSUE THREAD

**Issue by DietmarSchwertberger** [waf-project/waf#1657]
Hi!
I'm using an older version of waf to build wxPython Phoenix.
The 64 bit version of the Visual Studio 2015 compiler seems to use cp437 for output, at least with a german windows. So e.g. the umlaut u (ü) is output as character 0x81.
I'm not sure how to address this in a perfect way, but at least I think it would be a good idea to be a bit more robust in waflib\Context.py. How about adding "ignore" to these lines?

out = out.decode(sys.stdout.encoding or 'iso8859-1')
err = err.decode(sys.stdout.encoding or 'iso8859-1')

The compiler output is e.g. "Microsoft (R) C/C++-Optimierungscompiler Version 19.00.23026 für x64\r\n"
I think "ignore" should not cause problems.

Regards,

Dietmar

**Comment by ita1024** [comment]
Which Python version is used? And what is the value of sys.stdout.encoding?

**Comment by DietmarSchwertberger** [comment]
I'm trying to build for 3.5, 64 bit.
sys.stdout.encoding says cp1252
I would assume that the subprocess ignores this or has its own codepage.

**Comment by ita1024** [comment]
I doubt subprocess has anything to do with that. You may want to unset the environment variable VS_UNICODE_OUTPUT before calling waf configure, and perhaps call `chcp 1252 & waf configure`.

Ignoring encoding errors will lead to other problems, so this is not an option here.

**Comment by DietmarSchwertberger** [comment]
Thanks, cpcp 1252 before starting the build script solves the problem for me.
I don't think that this is transparent for people, though.
The error message is:
  msvc: Impossible to find a valid architecture for building (in setup_msvc)
I don't see how anyone should conclude to encoding issues from this.
For 32 bit Python everything worked fine for me.

**Comment by ita1024** [comment]
Do you mean that the 32-bit Python version did not have such a problem? Could this be a Python issue then?

**Comment by DietmarSchwertberger** [comment]
Sorry, this information was not 100% correct.
I successfully built the 32 bit version of wxPython first, using Visual Studio 2015 Express.
As Express did not have a 64 bit compiler, I had to switch to Visual Studio 2015 Community Edition.
I just checked the 32 bit build again and it has the same problem.
I have uninstalled Express already. With Community, both the 32 and the 64 bit compilers will output Umlaut characters:
Microsoft (R) C/C++-Optimierungscompiler Version 19.00.23026 für x86
Microsoft (R) C/C++-Optimierungscompiler Version 19.00.23026 für x64

Visual Studio 2012 seems to default to english output, so there were no problems:
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC>cl
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.40219.01 for 80x86

Default codepage for new cmd windows seems to be 850 (which is basically the same as 437).
Is it difficult to modify the error message, indicating that decoding with e.g. 1252 failed and the user may check the code page first?

**Comment by ita1024** [comment]
Yes it is. The config.log file contains the information already, does it not?

**Comment by ita1024** [comment]
Could you paste the error log? We do not have that version of visual studio here, and trying to make any change is a lot of guess work.

**Comment by DietmarSchwertberger** [comment]
Sorry for the delay. I'm working on wx only in the evening....
Please find attached the log.

I don't think that I would have found the cause from the log and without the Wing IDE debugger...
For me, of course I can add the chcp to the build script (not sure whether this has negative effects if someone will try using cygwin).
Would it be possible to query the actual codepage from subprocess.Popen by adding a chcp command at the beginning? Then you could have a look at the first lines of output and use the correct decoding.

Be careful about localization, though. For me the output looks like:
  D:\Python\Sources34\Phoenix>chcp
  Aktive Codepage: 850.

**Comment by ita1024** [comment]
Can you try 0e03aec82dfabefc9d104104fb0c18916a8db74b and paste the new logs and outputs?

**Comment by DietmarSchwertberger** [comment]
Here's the backtrace:

Setting top to                           : D:\Python\Sources34\Phoenix
Setting out to                           : D:\Python\Sources34\Phoenix\build\waf\3.5\x86\release
Checking for program CL                  : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\CL.exe
Traceback (most recent call last):
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Scripting.py", line 97, in w
af_entry_point
    run_commands()
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Scripting.py", line 153, in
run_commands
    ctx=run_command(cmd_name)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Scripting.py", line 146, in
run_command
    ctx.execute()
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Configure.py", line 128, in
execute
    super(ConfigurationContext,self).execute()
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Context.py", line 89, in exe
cute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Context.py", line 130, in re
curse
    user_function(self)
  File "D:\Python\Sources34\Phoenix\wscript", line 88, in configure
    conf.load('msvc')
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Configure.py", line 193, in
load
    if type(func)is type(Utils.readf):func(self)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Tools\msvc.py", line 483, in
 configure
    conf.autodetect(True)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Configure.py", line 224, in
fun
    return f(*k,**kw)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Tools\msvc.py", line 502, in
 autodetect
    compiler,version,path,includes,libdirs,arch=conf.detect_msvc(True)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Configure.py", line 224, in
fun
    return f(*k,**kw)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Tools\msvc.py", line 410, in
 detect_msvc
    versions=get_msvc_versions(conf)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Tools\msvc.py", line 399, in
 get_msvc_versions
    conf.gather_msvc_versions(lst)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Configure.py", line 224, in
fun
    return f(*k,**kw)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Tools\msvc.py", line 286, in
 gather_msvc_versions
    conf.gather_msvc_targets(versions,version,vc_path)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Configure.py", line 224, in
fun
    return f(*k,**kw)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Tools\msvc.py", line 218, in
 gather_msvc_targets
    targets.append((target,(realtarget,conf.get_msvc_version('msvc',version,target,os.path.join(vc_path,'vcvarsall.bat')
))))
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Configure.py", line 224, in
fun
    return f(*k,**kw)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Tools\msvc.py", line 100, in
 get_msvc_version
    conf.cmd_and_log(cxx+['/help'],env=env)
  File "D:\Python\Sources34\Phoenix\bin\waf3-1.7.15-9c6c439a6416a92b3e844736c4ef3c7b\waflib\Context.py", line 196, in cm
d_and_log
    out=out.decode(sys.stdout.encoding or'iso8859-1')
  File "D:\Python\Python35\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 474: character maps to <undefined>
Finished command: build_py (1.311s)
Finished command: build (2.935s)

D:\Python\Sources34\Phoenix>

**Comment by ita1024** [comment]
Errors are definitely unmasked (waf 1.8.20), so the problem is now visible so that the users can set the environment encoding if needed. Ignoring encoding errors can cause further problems and will not be applied.
