### ISSUE TITLE
Jython fix breaks failing Fortran compilation on MacOS

### ISSUE THREAD

**Issue by haraldkl** [waf-project/waf#1710]
Commit e0b080b seems to break failing (multi-threaded) compilations for Fortran (with Cython, Python 2.7). When a compilation error occurs, the build just hangs and never returns. Even if I interrupt it, I don't get the shell back. Here is what the trace upon manual abortion:

    ^CTraceback (most recent call last):
      File "/Users/klimach/Projects/apes/ateles/.waf-1.9.0-7f70e7ab4da027adee6851da98a3a6ce/waflib/processor.py", line 36, in <module>
    Traceback (most recent call last):
      File "/Users/klimach/Projects/apes/ateles/.waf-1.9.0-7f70e7ab4da027adee6851da98a3a6ce/waflib/processor.py", line 36, in <module>
    Traceback (most recent call last):
      File "/Users/klimach/Projects/apes/ateles/.waf-1.9.0-7f70e7ab4da027adee6851da98a3a6ce/waflib/processor.py", line 36, in <module>
    Traceback (most recent call last):
      File "/Users/klimach/Projects/apes/ateles/.waf-1.9.0-7f70e7ab4da027adee6851da98a3a6ce/waflib/processor.py", line 36, in <module>
        txt=sys.stdin.readline()
        KeyboardInterrupttxt=sys.stdin.readline()

    KeyboardInterrupt
        txt=sys.stdin.readline()
    KeyboardInterrupt
        txt=sys.stdin.readline()
    KeyboardInterrupt

Commit b2bcee4 works fine.

**Comment by haraldkl** [comment]
Might be something in my own extensions. Can not reproduce the problem with demos/fortran.

**Comment by ita1024** [comment]
No, I did not have time to complete the implementation and there were several problems with Python3.
Have a look at https://waf.io/ci/ from time to time to see if it is a known issue.

**Comment by haraldkl** [comment]
OK, thanks!

**Comment by ita1024** [comment]
The code is still broken due to a race condition in Runner.py that is more difficult to fix than I thought, so you may have to get back by a few revisions. Sorry for the trouble.

**Comment by haraldkl** [comment]
No trouble, really. Just thought it might have been something that went unnoticed. I already reverted to some earlier revision, thanks!

**Comment by ita1024** [comment]
Things should be back to normal now.

**Comment by haraldkl** [comment]
Yes, thanks. I can confirm that the issue is gone with the latest revision.
