### ISSUE TITLE
KeyError in color_gcc.py when msvc.py is also loaded

### ISSUE THREAD

**Issue by Vynce** [waf-project/waf#1732]
```
Traceback (most recent call last):
  File "xyz\tools\waf\waflib\Logs.py", line 142, in emit
    self.emit_override(record)
  File "xyz\tools\waf\waflib\Logs.py", line 154, in emit_override
    msg = self.formatter.format(record)
  File "xyz\tools\waf\waflib\extras\color_gcc.py", line 28, in format
    cmd = frame.f_locals['cmd']
KeyError: 'cmd'
Logged from file Logs.py, line 251
```

Printing `frame.f_code` and `frame.f_locals` in `color_gcc.py` reveals that msvc's `exec_command` function does not contain a local `cmd` variable:
```Python
<code object exec_command at 0269DF50, file "xyz\tools\waf\waflib\Tools\msvc.py", line 1052>
{'k': (['C:\\Program Files (x86)\\GNU Tools ARM Embedded\\4.9 2015q3\\bin\\arm-none-eabi-gcc.exe',
      '@c:\\users\\vynce\\appdata\\local\\temp\\tmp4p7_kr', '..\\..\\..\\ABC\\foo.c'],),
      'derived_class': <class 'waflib.Tools.msvc.c'>, 'kw': {'cwd': None, 'env': None}, 'self':
      {task 59743440: c foo.c -> foo.c.9.o}}
```

Here's a simple fix, but perhaps the correct fix is to change how msvc's `exec_command` function is monkeypatched somehow?
```Diff
diff --git a/waflib/extras/color_gcc.py b/waflib/extras/color_gcc.py
index c1eaedf..5f1ad5d 100644
--- a/waflib/extras/color_gcc.py
+++ b/waflib/extras/color_gcc.py
@@ -18,7 +18,7 @@ class ColorGCCFormatter(Logs.formatter):
                while frame:
                        func = frame.f_code.co_name
                        if func == 'exec_command':
-                               cmd = frame.f_locals['cmd']
+                               cmd = frame.f_locals.get('cmd')
                                if isinstance(cmd, list) and ('gcc' in cmd[0] or 'g++' in cmd[0]):
                                        lines = []
                                        for line in rec.msg.split('\n'):
```

**Comment by ita1024** [comment]
It is called colorgcc, expecting it to work with msvc is a bit of a stretch, is it not?

@zougloub ^^

**Comment by Vynce** [comment]
Ha! To clarify, we're actually using msvc and gcc for different targets in the same build, so we have both tools loaded. I have no expectation of color_gcc doing anything with the msvc output, but I'd like it to work with the msvc tool loaded. The example I gave above is actually from compiling a C file with gcc. I don't understand why the msvc tool is in the Python stack, but it appears that's why its `exec_command` function was monkeypatched in the first place (see 3b699e3fedadcf9aa8385155c2a209a42e98337a).

**Comment by ita1024** [comment]
8114914e62c862f4075bf2f6c53e28cdc8453275

**Comment by Vynce** [comment]
Thanks, that works for me!
