### ISSUE TITLE
MemoryError when running on grsec kernel

### ISSUE THREAD

**Issue by vedranmiletic** [waf-project/waf#1741]
Running on Debian unstable with grsec kernel

```
$ uname -a
Linux akari 4.5.0-2-grsec-amd64 #1 SMP Debian 4.5.3-2+grsec201605080858+1 (2016-05-09) x86_64 GNU/Linux
```

Waf 1.9.0pre2, as well as older versions, will give the following error:

```
$ python waf-1.9.0pre2
Traceback (most recent call last):
  File "waf-1.9.0pre2", line 166, in <module>
    from waflib import Scripting
  File "/home/vedranm/.waf-1.9.0-5d366183045d52ee41f50db792ee4df5/waflib/Scripting.py", line 6, in <module>
    from waflib import Utils,Configure,Logs,Options,ConfigSet,Context,Errors,Build,Node
  File "/home/vedranm/.waf-1.9.0-5d366183045d52ee41f50db792ee4df5/waflib/Configure.py", line 6, in <module>
    from waflib import ConfigSet,Utils,Options,Logs,Context,Build,Errors
  File "/home/vedranm/.waf-1.9.0-5d366183045d52ee41f50db792ee4df5/waflib/ConfigSet.py", line 6, in <module>
    from waflib import Logs,Utils
  File "/home/vedranm/.waf-1.9.0-5d366183045d52ee41f50db792ee4df5/waflib/Logs.py", line 6, in <module>
    from waflib import Utils,ansiterm
  File "/home/vedranm/.waf-1.9.0-5d366183045d52ee41f50db792ee4df5/waflib/ansiterm.py", line 9, in <module>
    from ctypes import Structure,windll,c_short,c_ushort,c_ulong,c_int,byref,c_wchar,POINTER,c_long
  File "/usr/lib/python2.7/ctypes/__init__.py", line 555, in <module>
    _reset_cache()
  File "/usr/lib/python2.7/ctypes/__init__.py", line 279, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError
```

**Comment by ita1024** [comment]
If Grsec is configured properly, then that's a Python bug: failed imports do not raise memory errors.

```shell
python -c "from ctypes import Structure,windll,c_short,c_ushort,c_ulong,c_int,byref,c_wchar,POINTER,c_long"
```

**Comment by ita1024** [comment]
(Waf also runs on Jython or on PyPy by the way)
