### ISSUE TITLE
C-like build failed with empty outputs in any task

### ISSUE THREAD

**Issue by artiomn** [waf-project/waf#1825]
```python
Traceback (most recent call last):
  File "d:\repos\my_build_system\src\waflib\Scripting.py", line 165, in waf_entry_point
    run_commands()
  File "d:\repos\my_build_system\src\waflib\Scripting.py", line 266, in run_commands
    ctx = run_command(cmd_name)
  File "d:\repos\my_build_system\src\waflib\Scripting.py", line 250, in run_command
    ctx.execute()
  File "d:\repos\my_build_system\src\buildlib\tools\project_generators\msvs.py", line 1109, in override_build_state
    old(ctx)
  File "d:\repos\my_build_system\src\buildlib\core\build_context.py", line 236, in execute
    self.execute_build()
  File "d:\repos\my_build_system\src\buildlib\core\build_context.py", line 356, in execute_build
    self.compile()
  File "d:\repos\my_build_system\src\waflib\Build.py", line 368, in compile
    self.producer.start()
  File "d:\repos\my_build_system\src\waflib\Runner.py", line 301, in start
    self.refill_task_list()
  File "d:\repos\my_build_system\src\waflib\Runner.py", line 196, in refill_task_list
    self.outstanding.extend(next(self.biter))
  File "d:\repos\my_build_system\src\waflib\Build.py", line 819, in get_build_iterator
    self.post_group()
  File "d:\repos\my_build_system\src\waflib\Build.py", line 780, in post_group
    f()
  File "d:\repos\my_build_system\src\waflib\TaskGen.py", line 227, in post
    v()
  File "d:\repos\my_build_system\src\waflib\Tools\ccroot.py", line 263, in apply_link
    objs = [t.outputs[0] for t in getattr(self, 'compiled_tasks', [])]
IndexError: list index out of range
```

Fix [`ccroot.py:263`]:
```diff
-objs = [t.outputs[0] for t in getattr(self, 'compiled_tasks', [])]
+objs = [t.outputs[0] for t in getattr(self, 'compiled_tasks', []) if t.outputs]
```

**Comment by ita1024** [comment]
Invalid: compiled tasks are meant to provide object files. Why did you add tasks that produce no object files in that list?

**Comment by artiomn** [comment]
Yes, It's my mistake, You're right.
I have passed .def file through compile tasks.
Must be passed through LINKFLAGS:
```python
class append_msvc_def_file(Task):
    """
    Task for append parameters to msvc linker
    """

    color = 'CYAN'

    def __init__(self, *k, **kw):
        self.uid = types.MethodType(task_uid_gen, self)
        super(append_msvc_def_file, self).__init__(*k, **kw)

    def runnable_status(self):
        # A little bit hack.
        def_file = self.inputs[0]
        self.generator.link_task.env.append_unique('LINKFLAGS', ['/def:"{}"'.
                                                   format(def_file.abspath())])

        return super(append_msvc_def_file, self).runnable_status()


@extension('.def')
def generate_exports(self, node):
    """
    Bind the .def extension to the msvc exports file linker parameter
    """

    if self.env.CC_NAME not in ['msvc']:
        return

    task = self.create_task('append_msvc_def_file', node)

    #try:
    #    self.compiled_tasks.append(task)
    #except AttributeError:
    #    self.compiled_tasks = [task]
```

Thank you.

**Comment by ita1024** [comment]
Source def files can be passed directly:
https://github.com/waf-project/waf/blob/master/demos/c/shlib/wscript_build#L8
