### ISSUE TITLE
Maintain lightweight environment setup script

### ISSUE THREAD

**Issue by alexforencich** [waf-project/waf#1854]
Should be a pretty simple feature to implement.  Waf should maintain an environment setup script (say, settings.sh, env.sh, etc.) that can be sourced to produce the same result as running ./waf shell, but without calling waf.  

The reason something like this is necessary is waf is a huge roadblock for running very large number of instances of a waf output program with waf --run.  The main problem is that waf will corrupt its own configuration if called too frequently (i.e. every 100 ms or so across 8 computers all looking at the same NFS mount).

**Comment by ita1024** [comment]
Detailed testcase? Error messages? Are you trying to run waf concurrently from the same folder or do you just have a filesystem that lets you write to deleted files?

**Comment by alexforencich** [comment]
Test case might be a little complex, the data is stored in a shared directory on a netapp and then nfs mounted on the nodes.  Not sure what's going on exactly, but get Python JSON errors almost immediately, and fixing that requires stopping everything running ./waf configure again.  It seems like waf is rewriting something on every run and that is causing things to get totally screwed up.  And at one point I started getting permission denied IO errors as well.  If I rsync the whole works to local storage on each node and run it from there with a 20 second delay between starting new instances on a given node, it seems to be working fine.  But it would be very nice to be able remove all the delay stuff and simply be able to source a file and run the executable directly.

**Comment by ita1024** [comment]
We do not use json anywhere, and data is not written unless necessary (something is built). We also have no routines to run resulting executables, and no shell is used by default, so the reason why you are asking for 'sourcing' is unclear to me.

You have not provided any instructions to reproduce the problem nor error messages so far.

**Comment by alexforencich** [comment]
Here is the permission denied trace:

    Build commands will be stored in build/compile_commands.json
    Traceback (most recent call last):
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 110, in waf_entry_point
        run_commands()
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 171, in run_commands
        ctx=run_command(cmd_name)
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 162, in run_command
        ctx.execute()
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Scripting.py", line 383, in execute
        return execute_method(self)
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Build.py", line 107, in execute
        self.execute_build()
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Build.py", line 121, in execute_build
        self.post_build()
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Build.py", line 276, in post_build
        m(self)
      File "waf-tools/clang_compilation_database.py", line 65, in write_compilation_database
        database_file.write(json.dumps(root, indent=2))
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Node.py", line 74, in write
        Utils.writef(self.abspath(),data,flags,encoding)
      File "/mnt/dcswitch/alex/Projects/ns3-hybrid/.waf-1.8.19-b1fc8f7baef51bd2db4c2971909a568d/waflib/Utils.py", line 107, in writef
        f=open(fname,m)
    IOError: [Errno 13] Permission denied: '/mnt/dcswitch/alex/Projects/ns3-hybrid/build/compile_commands.json'

This was generated by running waf with pssh across all 8 nodes like so:

    pssh -i -H "reactor0 reactor1 reactor2 reactor3 reactor4 reactor5 reactor6 reactor7" "cd /mnt/dcswitch/alex/Projects/ns3-hybrid && ./waf"

**Comment by alexforencich** [comment]
Ah, it seems waf --run and waf shell may be specific to ns-3.  I apologize for not being aware of what is an intrinsic feature of waf and what was grafted on by the ns-3 team.  I thought this was an intrinsic feature of waf, but appears to be implemented directly in the ns-3 top level wscript.  In that case, I'll have to look in to implementing this functionality in the ns-3 wscript file.

**Comment by ita1024** [comment]
Try running 'waf shell shell' or 'waf build build --run' just in case

**Comment by ita1024** [comment]
Reopen if you believe that this is our problem and you have additional information to provide.
