### ISSUE TITLE
migration 1.8.22 to 1.9

### ISSUE THREAD

**Issue by yag00** [waf-project/waf#1868]
I have 2 tasks : A and B.
A execute a test program(previously built) and generate a test report
B collect all test reports to generate a global report
Task B use all the output files from tasks A as inputs and generate one output file.

Everything works fine with waf 1.8.22.

But with waf 1.9, task B runnable_status() returns exception instead of ask later.
On the second run (./waf build), it works as expected.
(tried version 1.9.5 and 1.9.6 on Ubuntu 16.04 64bit)

Here is the stacktrace :
```
Build failed
Traceback (most recent call last):
  File ".waf-1.9.6-1ecbdf01fc72069e86a449e0b0ff8bc7/waflib/Runner.py", line 128, in task_status
    return tsk.runnable_status()
  File ".waf-1.9.6-1ecbdf01fc72069e86a449e0b0ff8bc7/waflib/Task.py", line 332, in runnable_status
    new_sig=self.signature()
  File ".waf-1.9.6-1ecbdf01fc72069e86a449e0b0ff8bc7/waflib/Task.py", line 318, in signature
    self.sig_explicit_deps()
  File ".waf-1.9.6-1ecbdf01fc72069e86a449e0b0ff8bc7/waflib/Task.py", line 375, in sig_explicit_deps
    upd(x.get_bld_sig())
  File ".waf-1.9.6-1ecbdf01fc72069e86a449e0b0ff8bc7/waflib/Node.py", line 468, in get_bld_sig
    ret=cache[self]=self.h_file()
  File ".waf-1.9.6-1ecbdf01fc72069e86a449e0b0ff8bc7/waflib/Node.py", line 457, in h_file
    return Utils.h_file(self.abspath())
  File ".waf-1.9.6-1ecbdf01fc72069e86a449e0b0ff8bc7/waflib/Utils.py", line 153, in h_file
    f=open(fname,'rb')
IOError: [Errno 2] No such file or directory ...
```

The Node.get_bld_sig() method has changed. The self.h_file() method raise the exception since the input file is not created yet. Raising a TaskNotReady exception (see below) fix the issue but i'm not sure this is the right way to do it.

```
def get_bld_sig(self):
	"""
	Returns a signature (see :py:meth:`waflib.Node.Node.h_file`) for the purpose
	of build dependency calculation. This method uses a per-context cache.

	:return: a hash representing the object contents
	:rtype: string or bytes
	"""
	# previous behaviour can be set by returning self.ctx.node_sigs[self] when a build node
	try:
		cache = self.ctx.cache_sig
	except AttributeError:
		cache = self.ctx.cache_sig = {}
	try:
		ret = cache[self]
	except KeyError:
		p = self.abspath()
		try:
			ret = cache[self] = self.h_file()
		except EnvironmentError as e:
			if self.isdir():
				# allow folders as build nodes, do not use the creation time
				st = os.stat(p)
				ret = cache[self] = Utils.h_list([p, st.st_ino, st.st_mode])
				return ret
			else:
				raise Errors.TaskNotReady
	return ret
```

**Comment by ita1024** [comment]
The build sees to be under-specified. What are the outputs of Task A and what are the inputs of Task B?

**Comment by yag00** [comment]
Task A run a test and output an xml test report => run the test program which produce an xml report
Task B takes all xml test report run by several Task A to output an html report.
Here is what I do : 

```
bld.add_group()
reports = []
for test in tests:
	testName = getName(test)
	node = bld.path.find_or_declare('report_%s.xml' % testName)

	bld.program(
		name		= testName,
		target		= testName,
		source		= [test],
		...
	)

	bld.test(
		program		= testName,
		report		= node,
	)

	reports.append(node)

bld.testreport(
	reports		= reports,
	output		= 'report.html'
)
```

**Comment by ita1024** [comment]
The method `bld.test` is not from us. What does that function do?

(by the way, just set `source = [node]` in the above)

**Comment by yag00** [comment]
fixed. issue was on my side. sorry!
