### ISSUE TITLE
waf configure gives gives exception tracebacks when using python 3.6.0

### ISSUE THREAD

**Issue by selsky** [waf-project/waf#1889]
```
$ python3 ./waf configure
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x10d7563c8>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x10d75deb8>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x10d75def0>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Popen.__del__ of <subprocess.Popen object at 0x10d75df28>>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 761, in __del__
TypeError: 'NoneType' object is not callable
[selsky@sidewinder ntpsec]$ vim /usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py
```
There was a similar error (but different) for python 2.6.4 in #1874

**Comment by selsky** [comment]
Manually reverting the patch from https://bugs.python.org/issue26741 (by hand) allows waf to complete successfully.  Should this be fixed in python upstream or waf?

**Comment by ita1024** [comment]
The problem is not fixable in Waf, see: http://bugs.python.org/issue29174

**Comment by selsky** [comment]
Thanks, I applied the patch in http://bugs.python.org/issue29174 locally and it cleared the warning messages.
