### ISSUE TITLE
runnable_status && dependencies on dynamically generated tasks

### ISSUE THREAD

**Issue by captainmalloc** [waf-project/waf#1919]
Hi,

it seems to me that 'Task.runnable_status()' method does imply that input nodes do exists in file system. Unfortunately this may not be true for dynamically generated tasks. 

Here above I created a small flow to show my point : 

```
#!/usr/bin/env python
# encoding: utf-8

APPNAME = 'Test'
VERSION = '1.0'

top = '.'
out = 'build'

from waflib import TaskGen, Task

def options(opts):
    opts.add_option('-n', type=int, default=10)
    
def configure(cnf):
    cnf.env.NUM = cnf.options.n

def build(bld):
    bld(features='GenConfigs', name='GenConfigs')
    bld(features='UseConfigs', name='UseConfigs')
    
@TaskGen.feature('GenConfigs')
def process_genConfigs(self):
    self.create_task(
        'genConfigs'
    )

class genConfigs(Task.Task):
    
    def run(self):
        self.more_tasks = []
        
        for i in range(self.env.NUM):
            tsk = self.generator.create_task(
                'genConfig',
                tgt = self.generator.bld.bldnode.make_node(str(i)+'.cfg')
            )
            tsk.set_run_after(self)
            self.more_tasks.append(tsk)
        
class genConfig(Task.Task):
    def run(self):
        self.exec_command(cmd="sleep 10")
        self.exec_command(cmd="touch " + self.outputs[0].abspath())
        
@TaskGen.feature('UseConfigs')
def process_useConfigs(self):
    
    self.create_task(
        'useConfigs',
    )
    
class useConfigs(Task.Task):
    
    def run(self):
        self.more_tasks = []
        
        for i in range(self.env.NUM):
            cfgNode = self.generator.bld.bldnode.make_node(str(i)+'.cfg')
            tsk = self.generator.create_task(
                'useConfig',
                src = cfgNode,
                tgt = cfgNode.change_ext('.txt')
            )
            tsk.set_run_after(self)
            self.more_tasks.append(tsk)

class useConfig(Task.Task):
    
    def runnable_status(self):
        if not self.inputs[0].exists():
            return Task.ASK_LATER
        
        return Task.Task.runnable_status(self)
    
    
    def run(self):
        print self.outputs[0]
        self.exec_command(cmd="touch " + self.outputs[0].abspath())
```

And here above the output:

```
adrsco[~/wafTest] waf distclean configure build
'distclean' finished successfully (0.011s)
Setting top to                           : /home/adrsco/wafTest 
Setting out to                           : /home/adrsco/wafTest/build 
'configure' finished successfully (0.013s)
Waf: Entering directory `/home/adrsco/wafTest/build'
[1/2] Running genConfigs
[2/2] Running useConfigs
[ 3/12] Creating build/0.cfg
[ 4/12] Creating build/1.cfg
[ 5/12] Creating build/2.cfg
[ 6/12] Creating build/3.cfg
[ 7/22] Creating build/4.cfg
[ 8/22] Creating build/5.cfg
[10/22] Creating build/6.cfg
[11/22] Creating build/7.cfg
Waf: Leaving directory `/home/adrsco/wafTest/build'
Build failed
Traceback (most recent call last):
  File "/opt/tools/waf/waf/1.9.8/bin/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Runner.py", line 128, in task_status
    return tsk.runnable_status()
  File "/opt/tools/waf/waf/1.9.8/bin/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 344, in runnable_status
    new_sig=self.signature()
  File "/opt/tools/waf/waf/1.9.8/bin/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 330, in signature
    self.sig_explicit_deps()
  File "/opt/tools/waf/waf/1.9.8/bin/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Task.py", line 387, in sig_explicit_deps
    upd(x.get_bld_sig())
  File "/opt/tools/waf/waf/1.9.8/bin/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 466, in get_bld_sig
    ret=cache[self]=self.h_file()
  File "/opt/tools/waf/waf/1.9.8/bin/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Node.py", line 455, in h_file
    return Utils.h_file(self.abspath())
  File "/opt/tools/waf/waf/1.9.8/bin/.waf-1.9.8-17756245c4cc550633dacf3b08eec42a/waflib/Utils.py", line 153, in h_file
    f=open(fname,'rb')
IOError: [Errno 2] No such file or directory: '/home/adrsco/wafTest/build/0.cfg'
```

And finally the solution I found, i.e. to overload 'runnable_status()' in the 'useConfig' Task:
```
...
class useConfig(Task.Task):
    
    def runnable_status(self):
        if not self.inputs[0].exists():
            return Task.ASK_LATER
        
        return Task.Task.runnable_status(self)
...
```

**Comment by ita1024** [comment]
1. 'Task.runnable_status()' method does *NOT* imply that input nodes do exists in file system (Node objects are an abstraction). A build order is simply calculated based on the task inputs and outputs relationships. This evaluation occurs once for each group of task objects under processing
2. Since the evaluation happens only once, tasks inserted dynamically (`more_tasks`) must provide the required `run_after` attributes; the build process will not re-evaluate the whole dependency constraints.
3. Your tasks `useconfig` and `genconfig` can be evaluated in arbitrary order so there is a race condition.
4. Checking too often for the presence of files on the filesystem usually leads to significant performance problems.

**Comment by captainmalloc** [comment]
1. How do you explain the IOError?
2. In the example I cannot specify the `run_after` as tasks have not yet been generated

**Comment by ita1024** [comment]
- The IOError is explained by point .1 above. This is the expected behaviour.
- If you say so. While reimplementing the runnable_status method in the manner that you did works, it is also inefficient and cannot be made the default behaviour.
