### ISSUE TITLE
UnicodeDecodeError when parsing the vswhere's output

### ISSUE THREAD

**Issue by bbalp** [waf-project/waf#1965]
Since the commit a65c7c0 an error has appeared when detecting the compilers available with the vswhere's output. This error seems to be related to an encoding issue. vswhere's output is localized according the default locale, not UTF-8. I am seeing this error because my computer run on a French windows and vswhere's is outputting some accentuated characters.

```
Setting top to                           : C:\waf\demos\c
Setting out to                           : C:\waf\demos\c\build
Checking for 'msvc' (C compiler)         : Traceback (most recent call last):
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Scripting.py", line 122, in waf_entry_point
    run_commands()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Scripting.py", line 183, in run_commands
    ctx=run_command(cmd_name)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Scripting.py", line 174, in run_command
    ctx.execute()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Context.py", line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Context.py", line 129, in recurse
    user_function(self)
  File "C:\waf\demos\c\wscript", line 21, in configure
    conf.load('compiler_c gnu_dirs')
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 155, in load
    func(self)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\compiler_c.py", line 23, in configure
    conf.load(compiler)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 155, in load
    func(self)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 541, in configure
    conf.autodetect(True)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 559, in autodetect
    compiler,version,path,includes,libdirs,cpu=conf.detect_msvc()
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 459, in detect_msvc
    return self.setup_msvc(self.get_msvc_versions())
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 467, in get_msvc_versions
    self.gather_vswhere_versions(dct)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "C:\waf\demos\c\waf-1.9.10-f85ace56fb46551039761743214f9116\waflib\Tools\msvc.py", line 310, in gather_vswhere_versions
    arr=json.loads(txt)
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 25: invalid start byte
```

I pull request immediately a fix, which is working at least for me and should work for everyone.

**Comment by bbalp** [comment]
As you mentioned in the pull request the fix I suggested only works with Python 2. The commit you provided which checks this requirement works fine.

Then I tested how all of this is going to work with Python 3 and the problem (encoding issues) is quite different, not related (or specific) to vswhere's output anymore, and not blocking for the building process (no crash).

So I can close this issue, related to vswhere's output, and I will post an issue about this specific situation using Python 3 as soon as I have a bit of time to.

Thank you.

**Comment by ita1024** [comment]
Are you implying that there is a detection issue using Python3?

**Comment by bbalp** [comment]
No detection issue, no build issue, nothing is blocking a full build of the demos/c project with Python 3, but definitely errors are displayed in the process, all related to encoding issues, when logging things for example if I remember correctly, maybe other things.

I have to retest it on Windows and save the output to post a descent issue about this.

**Comment by bbalp** [comment]
Definitely not related to your fix here.
