### ISSUE TITLE
build step fails when ctx.env contains a waflib.Node.Nod3, possibly incorrect serialization

### ISSUE THREAD

**Issue by hazelnusse** [waf-project/waf#1979]
I add a variable to the env in the configure step and it works fine, but I get this failure when running build. It seems that the serialization of waflib.Node.Nod3 objects does not result in a string when written to the c4che/_cache.py file and this causes a parsing error on the build step. If I fix the _cache.py file by adding quotes, the build step succeeds.

```
[I] luke.peterson@lpeterson-m0489 ~/t/waf> tree
.
├── include
├── waf
└── wscript

1 directory, 2 files
[I] luke.peterson@lpeterson-m0489 ~/t/waf> more ./wscript
#! /usr/bin/env python
# encoding: utf-8

top = '.'
out = 'build'

def configure(ctx):
    ctx.env.INCLUDES_FOO = ctx.path.find_node('include')
    ctx.env.INCLUDES_BAR = ['hello', 'bar']
    print(type(ctx.env.INCLUDES_FOO))
    print(ctx.env.INCLUDES_FOO)

def build(ctx):
    pass

[I] luke.peterson@lpeterson-m0489 ~/t/waf> ./waf --version
waf 1.9.12 (4e0eb61e50813c8880b2ed0d97854eb65b5953d7)
[I] luke.peterson@lpeterson-m0489 ~/t/waf> ./waf configure
Setting top to                           : /Users/luke.peterson/tmp/waf
Setting out to                           : /Users/luke.peterson/tmp/waf/build
<class 'waflib.Node.Nod3'>
/Users/luke.peterson/tmp/waf/include
'configure' finished successfully (0.007s)
[I] luke.peterson@lpeterson-m0489 ~/t/waf> ./waf build
Traceback (most recent call last):
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/Scripting.py", line 122, in waf_entry_point
    run_commands()
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/Scripting.py", line 183, in run_commands
    ctx=run_command(cmd_name)
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/Scripting.py", line 174, in run_command
    ctx.execute()
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/Scripting.py", line 368, in execute
    return execute_method(self)
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/Build.py", line 103, in execute
    self.load_envs()
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/Build.py", line 88, in load_envs
    env=ConfigSet.ConfigSet(x.abspath())
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/ConfigSet.py", line 13, in __init__
    self.load(filename)
  File "/Users/luke.peterson/tmp/waf/.waf-1.9.12-79f18015719bbaac5e7ab2428d451cd2/waflib/ConfigSet.py", line 152, in load
    tbl[g(2)]=eval(g(3))
  File "<string>", line 1
    /Users/luke.peterson/tmp/waf/include
    ^
SyntaxError: invalid syntax
[I] luke.peterson@lpeterson-m0489 ~/t/waf> more ./build/c4che/_cache.py
BINDIR = '/usr/local/bin'
INCLUDES_BAR = ['hello', 'bar']
INCLUDES_FOO = /Users/luke.peterson/tmp/waf/include
LIBDIR = '/usr/local/lib'
PREFIX = '/usr/local'
[I] luke.peterson@lpeterson-m0489 ~/t/waf> vim ./bu^C
[I] luke.peterson@lpeterson-m0489 ~/t/waf> vim ./build/c4che/_cache.py
[I] luke.peterson@lpeterson-m0489 ~/t/waf> more ./build/c4che/_cache.py
BINDIR = '/usr/local/bin'
INCLUDES_BAR = ['hello', 'bar']
INCLUDES_FOO = '/Users/luke.peterson/tmp/waf/include'
LIBDIR = '/usr/local/lib'
PREFIX = '/usr/local'
[I] luke.peterson@lpeterson-m0489 ~/t/waf> ./waf build
Waf: Entering directory `/Users/luke.peterson/tmp/waf/build'
Waf: Leaving directory `/Users/luke.peterson/tmp/waf/build'
'build' finished successfully (0.006s)
[I] luke.peterson@lpeterson-m0489 ~/t/waf>
```

**Comment by hazelnusse** [comment]
[Archive.zip](https://github.com/waf-project/waf/files/1048457/Archive.zip)

**Comment by ita1024** [comment]
This works as expected, Node objects are not meant to be serialized in `env` objects.

**Comment by hazelnusse** [comment]
Please update the table in section 10.3.3:
![screen shot 2017-06-02 at 10 42 00 am](https://cloud.githubusercontent.com/assets/63265/26737715/2e97bd12-4780-11e7-8895-abe3d5ac32cb.png)
