### ISSUE TITLE
waf2.0.0pre4: Using "swig" tool skips some tasks?

### ISSUE THREAD

**Issue by q-p** [waf-project/waf#1982]
This is a bit difficult to describe / diagnose. When using the "swig" tool to build Python wrappers for C++ code, some tasks in my build are no longer executed (not all of these skipped ones are actually directly related to the SWIG wrapper, but they should be used by it). This worked ok in waf 1.9.

My set-up is essentially as follows:
```py
bld.shlib(target='Flis', features='cxx', source=bld.path.ant_glob('flis/*.cpp'))
bld.shlib(target='Flucs', features='cxx', source=bld.path.ant_glob('flucs/*.cpp'), use='Flis')
bld(target='_Flucs', features='cxx cxxshlib pyext', source='Flucs.i', use='Flucs')
```

So that the Python interface depends on `libFlucs` which depends on `libFlis`.

Now the problem is that in my case some `.cpp` files (at least from `Flucs`) are never compiled, and neither `libFlucs` nor the Python extension (`_Flucs`) is ever actually linked.

The output of a first clean build looks as follows:
```
~/D/d/d/negev (feature/waf20|✚4…)> ./waf
Waf: Entering directory `negev/build'
[ 1/54] Processing py/Flucs.i
[ 2/54] Compiling infrastructure/src/Preprocessing/MeshConsistency.cpp
[ 3/54] Compiling infrastructure/src/TimeIntegration/TimeStep.cpp
[ 4/54] Compiling infrastructure/src/Parameter/DiscriminatedGroupNode.cpp
[ 5/54] Compiling infrastructure/src/TimeIntegration/TimeIntegrationBase.cpp
[ 6/54] Compiling infrastructure/src/SpatialDiscretization/DiscretizationSelectionPara.cpp
[ 7/54] Compiling infrastructure/src/Parameter/ArrayNode.cpp
[ 8/54] Compiling infrastructure/src/Parallel/UtilsMPI.cpp
[ 9/54] Compiling infrastructure/src/SpatialDiscretization/DiscretizationParaBase.cpp
[10/54] Compiling infrastructure/src/SpatialDiscretization/DiscretizationFactory.cpp
[11/54] Compiling infrastructure/src/Parallel/Threading.cpp
[12/54] Compiling infrastructure/src/Parallel/ThreadedCommunicationContext.cpp
[13/54] Compiling infrastructure/src/ReferenceElement/NodalBasisFunctions.cpp
[14/54] Compiling infrastructure/src/Parallel/SynchronizingEvent.cpp
[15/54] Compiling infrastructure/src/DiscreteEquation/ReferenceData.cpp
[16/54] Compiling infrastructure/src/Common/VariableIdentifier.cpp
[17/54] Compiling infrastructure/src/Parallel/CommunicationBuffersMPI.cpp
[18/54] Compiling infrastructure/src/SpatialDiscretization/Instantiations.cpp
[19/54] Compiling infrastructure/src/TimeIntegration/ExplicitRungeKutta.cpp
[20/54] Compiling infrastructure/src/Parallel/CommunicationBuffersGASPI.cpp
[21/54] Compiling infrastructure/src/Preprocessing/OversetGridsProcessor.cpp
[22/54] Compiling infrastructure/src/Parallel/GaspiUtils.cpp
[23/54] Compiling infrastructure/src/Distributed/OversetGridsCommunication.cpp
[24/54] Compiling infrastructure/src/Parallel/CommunicationBuffersBase.cpp
[25/54] Compiling infrastructure/src/Preprocessing/FaceBasedMeshAdapter.cpp
[26/54] Compiling infrastructure/src/Distributed/Instantiations.cpp
[27/54] Compiling infrastructure/src/ReferenceElement/DistanceFromSurfaceElement.cpp
[28/54] Compiling infrastructure/src/Distributed/FaceBasedMeshPreprocessingArguments.cpp
[29/54] Compiling infrastructure/src/TimeIntegration/ButcherTableau.cpp
[30/54] Compiling infrastructure/src/Parameter/ParameterHelper.cpp
[31/54] Compiling infrastructure/src/Distributed/FSDataTransfer.cpp
[32/54] Compiling infrastructure/src/Parameter/Node.cpp
[33/54] Compiling infrastructure/src/ReferenceElement/Quadrature.cpp
[34/54] Compiling infrastructure/src/Parameter/GroupNode.cpp
[35/54] Compiling infrastructure/src/DiscreteEquation/BoundaryIntegralValues.cpp
[36/54] Compiling infrastructure/src/Preprocessing/Preprocessor.cpp
[37/54] Compiling build/py/Flucs.swigwrap_1.cxx
[38/54] Linking build/libFlis.dylib
Waf: Leaving directory `negev/build'
'build' finished successfully (42.121s)
```

As you can see, the tasks 39 to 54 are never executed. If i now repeat the build, waf occasionally compiles one of the missing files:
```
~/D/d/d/negev (feature/waf20|✚4…)> ./waf
Waf: Entering directory `negev/build'
[38/54] Compiling src/SpatialDiscretization/VenkatakrishnanPara.cpp
Waf: Leaving directory `negev/build'
'build' finished successfully (1.582s)
~/D/d/d/negev (feature/waf20|✚4…)> ./waf
Waf: Entering directory `negev/build'
Waf: Leaving directory `negev/build'
'build' finished successfully (0.090s)
~/D/d/d/negev (feature/waf20|✚4…)> ./waf
Waf: Entering directory `negev/build'
[38/54] Compiling src/SpatialDiscretization/LinearReconstruction.cpp
Waf: Leaving directory `negev/build'
'build' finished successfully (1.883s)
```

The weird thing is that without the swig tool, at least the C++ shared libraries seem to get build OK, so swig seems to play a role.

The `playground` swig example seems to exhibit part of the problem, because there, the python extension is also never built.

**Comment by ita1024** [comment]
I realized that a few unit tests were failing. Can you try a more recent revision (3e1e6586e51c24a9ee9bce838eb0c1ee7609cba9)?

**Comment by q-p** [comment]
With this change, all the .cpp files are actually compiled, but the link step for the SWIG Python extension `_Flucs` is still lost somewhere. When I add the "dynamic" build step from #1981 back in, then the link-task `libFlucs` is also not executed.

The `playground/swig` example still shows the failure to build the Python extension as well.

My build output now looks like this (compared to the previous output)
```
maven@feuerlilie ~/D/d/d/negev (feature/waf20|✚4…)> ./waf
Waf: Entering directory `negev/build'
[ 1/54] Processing py/Flucs.i
[ 2/54] Compiling infrastructure/src/Preprocessing/MeshConsistency.cpp
[ 3/54] Compiling infrastructure/src/Parameter/DiscriminatedGroupNode.cpp
[ 4/54] Compiling infrastructure/src/TimeIntegration/TimeStep.cpp
[ 5/54] Compiling infrastructure/src/TimeIntegration/TimeIntegrationBase.cpp
[ 6/54] Compiling infrastructure/src/SpatialDiscretization/DiscretizationSelectionPara.cpp
[ 7/54] Compiling infrastructure/src/Parameter/ArrayNode.cpp
[ 8/54] Compiling infrastructure/src/Parallel/UtilsMPI.cpp
[ 9/54] Compiling infrastructure/src/SpatialDiscretization/DiscretizationParaBase.cpp
[10/54] Compiling infrastructure/src/Parallel/GaspiUtils.cpp
[11/54] Compiling infrastructure/src/SpatialDiscretization/DiscretizationFactory.cpp
[12/54] Compiling infrastructure/src/Parallel/Threading.cpp
[13/54] Compiling infrastructure/src/Parallel/ThreadedCommunicationContext.cpp
[14/54] Compiling infrastructure/src/ReferenceElement/NodalBasisFunctions.cpp
[15/54] Compiling infrastructure/src/Parallel/SynchronizingEvent.cpp
[16/54] Compiling infrastructure/src/DiscreteEquation/ReferenceData.cpp
[17/54] Compiling infrastructure/src/Common/VariableIdentifier.cpp
[18/54] Compiling infrastructure/src/Preprocessing/Preprocessor.cpp
[19/54] Compiling infrastructure/src/Parallel/CommunicationBuffersMPI.cpp
[20/54] Compiling infrastructure/src/SpatialDiscretization/Instantiations.cpp
[21/54] Compiling infrastructure/src/Parallel/CommunicationBuffersGASPI.cpp
[22/54] Compiling infrastructure/src/ReferenceElement/DistanceFromSurfaceElement.cpp
[23/54] Compiling infrastructure/src/Preprocessing/OversetGridsProcessor.cpp
[24/54] Compiling infrastructure/src/Parallel/CommunicationBuffersBase.cpp
[25/54] Compiling infrastructure/src/Distributed/OversetGridsCommunication.cpp
[26/54] Compiling infrastructure/src/Preprocessing/FaceBasedMeshAdapter.cpp
[27/54] Compiling infrastructure/src/Distributed/Instantiations.cpp
[28/54] Compiling infrastructure/src/TimeIntegration/ExplicitRungeKutta.cpp
[29/54] Compiling infrastructure/src/Distributed/FaceBasedMeshPreprocessingArguments.cpp
[30/54] Compiling infrastructure/src/TimeIntegration/ButcherTableau.cpp
[31/54] Compiling infrastructure/src/Parameter/ParameterHelper.cpp
[32/54] Compiling infrastructure/src/Distributed/FSDataTransfer.cpp
[33/54] Compiling infrastructure/src/Parameter/Node.cpp
[34/54] Compiling infrastructure/src/ReferenceElement/Quadrature.cpp
[35/54] Compiling infrastructure/src/Parameter/GroupNode.cpp
[36/54] Compiling infrastructure/src/DiscreteEquation/BoundaryIntegralValues.cpp
[37/54] Compiling src/SpatialDiscretization/ConstantReconstruction.cpp
[38/54] Compiling src/SpatialDiscretization/LinearReconstruction.cpp
[39/54] Compiling src/SpatialDiscretization/FaceIntegrationDiscretizationParaBase.cpp
[40/54] Compiling src/DiscreteEquation/PhysicalVariables.cpp
[41/54] Compiling src/SpatialDiscretization/BarthJespersenPara.cpp
[42/54] Compiling src/LinearSolver/Instantiations.cpp
[43/54] Compiling src/TimeIntegration/ImplicitEuler.cpp
[44/54] Compiling src/LinearSolver/LinearSolverFactory.cpp
[45/54] Compiling src/SpatialDiscretization/VenkatakrishnanPara.cpp
[46/54] Compiling src/SpatialDiscretization/PrepareFaceBasedComputationalMesh.cpp
[47/54] Compiling src/SpatialDiscretization/FiniteVolumeDiscretizationParaBase.cpp
[48/54] Compiling src/DiscreteEquation/ReferenceDataEulerRANSConvection.cpp
[49/54] Compiling src/SpatialDiscretization/DGDiscretizationParaBase.cpp
[50/54] Compiling src/SpatialDiscretization/LimitedLinearReconstruction.cpp
[51/54] Compiling build/py/Flucs.swigwrap_1.cxx
[52/54] Linking build/libFlis.dylib
[53/54] Linking build/libFlucs.dylib
[54/55] Compiling build/py/Flucs.pyc
Waf: Leaving directory `negev/build'
'build' finished successfully (56.486s)
```

A second build invocation then notices that something is amiss and does it:
```
~/D/d/d/negev (feature/waf20|✚4…)> ./waf
Waf: Entering directory `negev/build'
[54/54] Linking build/py/_Flucs.so
Waf: Leaving directory `negev/build'
'build' finished successfully (0.207s)
```

**Comment by q-p** [comment]
`waflib/Runner.py:240` attempts to use `update` which results in `AttributeError: 'collections.deque' object has no attribute 'update'`. After changing that to `extend` my build seems to complete as expected.

Now to figure out how to use the new `.weight` attribute to compile some files earlier than others (which was the original reason for me trying out the 2.0 pre-release ;)).

**Comment by ita1024** [comment]
Some more work was still needed on the priority system. Please suggest other variable names if you have a better candidate:
https://github.com/waf-project/waf/blob/waf-2.0/waflib/Task.py#L156

Here is how to have link tasks execute as early as possible:
https://github.com/waf-project/waf/blob/waf-2.0/waflib/Tools/ccroot.py#L134

**Comment by q-p** [comment]
This version seems worse again than the in-between version I tried (which was f75de87 + the rename of `update` to `extend`). The current master (0cebd3bd) doesn't link `libFlucs` again (although that might just be because the assertion failure happens before it finishes?), and fails with an assertion failure:

```
Waf: Entering directory `build'
[ 1/57] Processing py/Flucs.i
[ 2/57] Processing src/LinearSolver/Instantiations.cppgen
[ 3/57] Processing src/SpatialDiscretization/Instantiations.cppgen
[ 4/57] Processing tools/doxygen/Flucs.doxy
[ 5/61] Compiling build/src/LinearSolver/InstantiationJacobi5.cpp
[ 6/61] Compiling build/src/LinearSolver/InstantiationJacobi24.cpp
[ 7/61] Compiling build/src/LinearSolver/InstantiationJacobi20.cpp
[ 8/68] Compiling build/src/LinearSolver/InstantiationJacobi6.cpp
[ 9/68] Compiling build/src/SpatialDiscretization/InstantiationFVRANSSAneg.cpp
[10/68] Compiling build/src/SpatialDiscretization/InstantiationFVEuler.cpp
[11/68] Compiling build/src/SpatialDiscretization/InstantiationDG1NavierStokes.cpp
[12/68] Compiling build/src/SpatialDiscretization/InstantiationDG0Euler.cpp
[13/68] Compiling build/src/SpatialDiscretization/InstantiationFVNavierStokes.cpp
[14/68] Compiling build/src/SpatialDiscretization/InstantiationDG1RANSSAneg.cpp
[15/68] Compiling build/src/SpatialDiscretization/InstantiationDG1Euler.cpp
sh: latex: command not found
error: Problems running latex. Check your installation or look for typos in _formulas.tex and check _formulas.log!
sh: dvips: command not found
error: Problems running dvips. Check your installation!
[16/68] Compiling infrastructure/src/TimeIntegration/TimeIntegrationBase.cpp
[17/68] Compiling infrastructure/src/Parallel/SynchronizingEvent.cpp
[18/68] Compiling infrastructure/src/Parallel/ThreadedCommunicationContext.cpp
[19/68] Compiling infrastructure/src/TimeIntegration/ExplicitRungeKutta.cpp
[20/68] Compiling infrastructure/src/Distributed/Instantiations.cpp
[21/68] Compiling infrastructure/src/SpatialDiscretization/DiscretizationFactory.cpp
[22/68] Compiling infrastructure/src/ReferenceElement/NodalBasisFunctions.cpp
[23/68] Compiling infrastructure/src/Common/VariableIdentifier.cpp
[24/68] Compiling infrastructure/src/TimeIntegration/ButcherTableau.cpp
[25/68] Compiling infrastructure/src/Parallel/CommunicationBuffersMPI.cpp
[26/68] Compiling infrastructure/src/SpatialDiscretization/DiscretizationSelectionPara.cpp
[27/68] Compiling infrastructure/src/Distributed/FaceBasedMeshPreprocessingArguments.cpp
[28/68] Compiling infrastructure/src/Parameter/ParameterHelper.cpp
[29/68] Compiling infrastructure/src/Preprocessing/MeshConsistency.cpp
[30/68] Compiling infrastructure/src/Parallel/UtilsMPI.cpp
[31/68] Compiling infrastructure/src/Distributed/FSDataTransfer.cpp
[32/68] Compiling infrastructure/src/Preprocessing/OversetGridsProcessor.cpp
[33/68] Compiling infrastructure/src/Parallel/CommunicationBuffersBase.cpp
[34/68] Compiling infrastructure/src/Parallel/GaspiUtils.cpp
[35/68] Compiling infrastructure/src/Parallel/Threading.cpp
[36/68] Compiling infrastructure/src/Parameter/Node.cpp
[37/68] Compiling infrastructure/src/DiscreteEquation/ReferenceData.cpp
[38/68] Compiling infrastructure/src/ReferenceElement/Quadrature.cpp
[39/68] Compiling infrastructure/src/SpatialDiscretization/DiscretizationParaBase.cpp
[40/68] Compiling infrastructure/src/DiscreteEquation/BoundaryIntegralValues.cpp
[41/68] Compiling infrastructure/src/Parameter/GroupNode.cpp
[42/68] Compiling infrastructure/src/Parallel/CommunicationBuffersGASPI.cpp
[43/68] Compiling infrastructure/src/TimeIntegration/TimeStep.cpp
[44/68] Compiling infrastructure/src/Preprocessing/Preprocessor.cpp
[45/68] Compiling infrastructure/src/SpatialDiscretization/Instantiations.cpp
[46/68] Compiling infrastructure/src/ReferenceElement/DistanceFromSurfaceElement.cpp
[47/68] Compiling infrastructure/src/Parameter/DiscriminatedGroupNode.cpp
[48/68] Compiling infrastructure/src/Distributed/OversetGridsCommunication.cpp
[49/68] Compiling infrastructure/src/Parameter/ArrayNode.cpp
[50/68] Compiling infrastructure/src/Preprocessing/FaceBasedMeshAdapter.cpp
[51/68] Compiling src/SpatialDiscretization/BarthJespersenPara.cpp
[52/68] Compiling src/SpatialDiscretization/LimitedLinearReconstruction.cpp
[53/68] Compiling src/SpatialDiscretization/PrepareFaceBasedComputationalMesh.cpp
[54/68] Compiling src/SpatialDiscretization/DGDiscretizationParaBase.cpp
[55/68] Compiling src/SpatialDiscretization/FaceIntegrationDiscretizationParaBase.cpp
[56/68] Compiling src/DiscreteEquation/PhysicalVariables.cpp
[57/68] Compiling src/TimeIntegration/ImplicitEuler.cpp
[58/68] Compiling src/SpatialDiscretization/ConstantReconstruction.cpp
[59/68] Compiling src/SpatialDiscretization/LinearReconstruction.cpp
[60/68] Compiling src/DiscreteEquation/ReferenceDataEulerRANSConvection.cpp
[61/68] Compiling src/LinearSolver/LinearSolverFactory.cpp
[62/68] Compiling src/LinearSolver/Instantiations.cpp
[63/68] Compiling src/SpatialDiscretization/VenkatakrishnanPara.cpp
[64/68] Compiling src/SpatialDiscretization/FiniteVolumeDiscretizationParaBase.cpp
[65/68] Compiling build/py/Flucs.swigwrap_2.cxx
[66/68] Linking build/libFlis.dylib
[67/69] Compiling build/py/Flucs.pyc
Waf: Leaving directory `build'
Traceback (most recent call last):
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Scripting.py", line 122, in waf_entry_point
    run_commands()
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Scripting.py", line 183, in run_commands
    ctx=run_command(cmd_name)
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Scripting.py", line 174, in run_command
    ctx.execute()
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Scripting.py", line 368, in execute
    return execute_method(self)
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Build.py", line 93, in execute
    self.execute_build()
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Build.py", line 100, in execute_build
    self.compile()
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Build.py", line 167, in compile
    self.producer.start()
  File ".waf-2.0.0-c90289b5b6302739f627236f3df454b6/waflib/Runner.py", line 244, in start
    assert not self.incomplete
AssertionError
```

**Comment by ita1024** [comment]
Thanks for reporting this! The assertion was valid as I forgot to update the Swig extension.

**Comment by q-p** [comment]
Weird, I'm still hitting the same assertion with 6a638625. Maybe some of my other (semi-)dynamic build tasks also need some changes (doxygen? cppgen compiler with unknown output files from the book example? python .py => .pyc?)?

```
Waf: Entering directory `build'
[ 1/57] Processing py/Flucs.i
[ 2/57] Processing src/LinearSolver/Instantiations.cppgen
[ 3/57] Processing src/SpatialDiscretization/Instantiations.cppgen
[ 4/57] Processing tools/doxygen/Flucs.doxy
[ 5/61] Compiling build/src/LinearSolver/InstantiationJacobi5.cpp
[ 6/61] Compiling build/src/LinearSolver/InstantiationJacobi24.cpp
[ 7/61] Compiling build/src/LinearSolver/InstantiationJacobi20.cpp
[ 8/68] Compiling build/src/LinearSolver/InstantiationJacobi6.cpp
[ 9/68] Compiling build/src/SpatialDiscretization/InstantiationFVRANSSAneg.cpp
[10/68] Compiling build/src/SpatialDiscretization/InstantiationFVEuler.cpp
[11/68] Compiling build/src/SpatialDiscretization/InstantiationDG1NavierStokes.cpp
[12/68] Compiling build/src/SpatialDiscretization/InstantiationDG0Euler.cpp
[13/68] Compiling build/src/SpatialDiscretization/InstantiationFVNavierStokes.cpp
[14/68] Compiling build/src/SpatialDiscretization/InstantiationDG1RANSSAneg.cpp
[15/68] Compiling build/src/SpatialDiscretization/InstantiationDG1Euler.cpp
[16/68] Compiling infrastructure/src/DiscreteEquation/ReferenceData.cpp
[17/68] Compiling infrastructure/src/ReferenceElement/Quadrature.cpp
[18/68] Compiling infrastructure/src/Parallel/ThreadedCommunicationContext.cpp
[19/68] Compiling infrastructure/src/TimeIntegration/ButcherTableau.cpp
[20/68] Compiling infrastructure/src/SpatialDiscretization/DiscretizationSelectionPara.cpp
[21/68] Compiling infrastructure/src/SpatialDiscretization/DiscretizationFactory.cpp
[22/68] Compiling infrastructure/src/TimeIntegration/TimeIntegrationBase.cpp
[23/68] Compiling infrastructure/src/Distributed/FaceBasedMeshPreprocessingArguments.cpp
[24/68] Compiling infrastructure/src/Parameter/ParameterHelper.cpp
[25/68] Compiling infrastructure/src/Common/VariableIdentifier.cpp
[26/68] Compiling infrastructure/src/Parallel/CommunicationBuffersMPI.cpp
[27/68] Compiling infrastructure/src/TimeIntegration/TimeStep.cpp
[28/68] Compiling infrastructure/src/Preprocessing/MeshConsistency.cpp
[29/68] Compiling infrastructure/src/Parameter/ArrayNode.cpp
[30/68] Compiling infrastructure/src/Distributed/FSDataTransfer.cpp
[31/68] Compiling infrastructure/src/Parallel/GaspiUtils.cpp
[32/68] Compiling infrastructure/src/Preprocessing/OversetGridsProcessor.cpp
[33/68] Compiling infrastructure/src/SpatialDiscretization/Instantiations.cpp
[34/68] Compiling infrastructure/src/ReferenceElement/NodalBasisFunctions.cpp
[35/68] Compiling infrastructure/src/Preprocessing/FaceBasedMeshAdapter.cpp
[36/68] Compiling infrastructure/src/Parallel/SynchronizingEvent.cpp
[37/68] Compiling infrastructure/src/Parallel/Threading.cpp
[38/68] Compiling infrastructure/src/Parallel/UtilsMPI.cpp
[39/68] Compiling infrastructure/src/Parameter/Node.cpp
[40/68] Compiling infrastructure/src/ReferenceElement/DistanceFromSurfaceElement.cpp
[41/68] Compiling infrastructure/src/Parameter/GroupNode.cpp
[42/68] Compiling infrastructure/src/Parallel/CommunicationBuffersGASPI.cpp
[43/68] Compiling infrastructure/src/Preprocessing/Preprocessor.cpp
[44/68] Compiling infrastructure/src/SpatialDiscretization/DiscretizationParaBase.cpp
[45/68] Compiling infrastructure/src/DiscreteEquation/BoundaryIntegralValues.cpp
[46/68] Compiling infrastructure/src/Parallel/CommunicationBuffersBase.cpp
[47/68] Compiling infrastructure/src/Distributed/OversetGridsCommunication.cpp
[48/68] Compiling infrastructure/src/Parameter/DiscriminatedGroupNode.cpp
[49/68] Compiling infrastructure/src/TimeIntegration/ExplicitRungeKutta.cpp
[50/68] Compiling infrastructure/src/Distributed/Instantiations.cpp
[51/68] Compiling src/SpatialDiscretization/FaceIntegrationDiscretizationParaBase.cpp
[52/68] Compiling src/SpatialDiscretization/BarthJespersenPara.cpp
[53/68] Compiling src/SpatialDiscretization/LimitedLinearReconstruction.cpp
[54/68] Compiling src/SpatialDiscretization/ConstantReconstruction.cpp
[55/68] Compiling src/SpatialDiscretization/FiniteVolumeDiscretizationParaBase.cpp
[56/68] Compiling src/DiscreteEquation/PhysicalVariables.cpp
[57/68] Compiling src/LinearSolver/Instantiations.cpp
[58/68] Compiling src/SpatialDiscretization/DGDiscretizationParaBase.cpp
[59/68] Compiling src/TimeIntegration/ImplicitEuler.cpp
[60/68] Compiling src/SpatialDiscretization/PrepareFaceBasedComputationalMesh.cpp
[61/68] Compiling src/SpatialDiscretization/VenkatakrishnanPara.cpp
[62/68] Compiling src/DiscreteEquation/ReferenceDataEulerRANSConvection.cpp
[63/68] Compiling src/SpatialDiscretization/LinearReconstruction.cpp
[64/68] Compiling src/LinearSolver/LinearSolverFactory.cpp
[65/68] Compiling build/py/Flucs.swigwrap_2.cxx
[66/68] Linking build/libFlis.dylib
[67/69] Compiling build/py/Flucs.pyc
Waf: Leaving directory `build'
Traceback (most recent call last):
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Scripting.py", line 122, in waf_entry_point
    run_commands()
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Scripting.py", line 183, in run_commands
    ctx=run_command(cmd_name)
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Scripting.py", line 174, in run_command
    ctx.execute()
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Scripting.py", line 368, in execute
    return execute_method(self)
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Build.py", line 93, in execute
    self.execute_build()
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Build.py", line 100, in execute_build
    self.compile()
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Build.py", line 167, in compile
    self.producer.start()
  File ".waf-2.0.0-d14a3eb573c138679c7f4d2781ba07e2/waflib/Runner.py", line 244, in start
    assert not self.incomplete
AssertionError
```

**Comment by ita1024** [comment]
I could not foresee that there were more swig-like extensions that can set dependencies after the build starts. The new implementation should support such cases.

**Comment by q-p** [comment]
I tested c49a74dd (which includes your rewrite), and my build works fine again. Thanks.
