### ISSUE TITLE
Error on ctx.load('msvc') when run from the MSYS2 shell 

### ISSUE THREAD

**Issue by dbogdanov** [waf-project/waf#1987]
Waf fails with error on ```ctx.load('msvc')``` when run from the MSYS2 shell 

```
Traceback (most recent call last):
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 122, in waf_entry_point
    run_commands()
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 183, in run_commands
    ctx=run_command(cmd_name)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Scripting.py", line 174, in run_command
    ctx.execute()
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Context.py", line 129, in recurse
    user_function(self)
  File "/home/User/essentia/wscript", line 238, in configure
    ctx.load('compiler_cxx compiler_c msvc')
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 155, in load
    func(self)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/msvc.py", line 541, in configure
    conf.autodetect(True)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 177, in fun
    return f(*k,**kw)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/msvc.py", line 559, in autodetect
    compiler,version,path,includes,libdirs,cpu=conf.detect_msvc()
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 177, in fun
    return f(*k,**kw)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/msvc.py", line 459, in detect_msvc
    return self.setup_msvc(self.get_msvc_versions())
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 177, in fun
    return f(*k,**kw)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/msvc.py", line 463, in get_msvc_versions
    self.gather_icl_versions(dct)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 177, in fun
    return f(*k,**kw)
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Tools/msvc.py", line 359, in gather_icl_versions
    except WindowsError:
NameError: global name 'WindowsError' is not defined
```

**Comment by ita1024** [comment]
Works for us https://waf.io/cilog/?jobnum=183&jobname=waf20-windows10-msys2 so this may be an msys2 regression. Which version of Python are you using?

**Comment by dbogdanov** [comment]
I am running waf from the MSYS2 MinGW 64-bit command line.

```
Python 2.7.11 (default, Mar  4 2016, 10:54:03)
[GCC 4.9.2] on msys
```

**Comment by ita1024** [comment]
Could you try with Python3 in msys2? Is `WindowsError` undefined there too?

**Comment by ita1024** [comment]
The winreg functions https://docs.python.org/2/library/_winreg.html#_winreg.EnumValue do raise `WindowsError`, and there is no particular import required. Try updating your msys2/python2 versions too.

**Comment by dbogdanov** [comment]
No problem with Python3.

**Comment by ita1024** [comment]
The exception name WindowsError should be defined in Python2 so this is a bug in your msys/Python2 version. Since that version is already obsolete, we will not make any change in Waf 1.9.

Note: The branch waf-2.0 uses `OSError` instead of `WindowsError`, but we will not apply such a change to waf 1.9.
