### ISSUE TITLE
Could not build a python embedded interpreter in MSYS2 MinGW

### ISSUE THREAD

**Issue by dbogdanov** [waf-project/waf#1988]
I am trying to build a Python extension using MSYS2 MinGW 64-bit console with ```mingw-w64-x86_64-gcc``` and ``mingw-w64-i686-python2``` packages installed.

waf configuration fails with 

```
------------------------------------------------------------------
Testing pyembed configuration
==>

#include <Python.h>
#ifdef __cplusplus
extern "C" {
#endif
        void Py_Initialize(void);
        void Py_Finalize(void);
#ifdef __cplusplus
}
#endif
int main(int argc, char **argv)
{
   (void)argc; (void)argv;
   Py_Initialize();
   Py_Finalize();
   return 0;
}

<==
[1/2] Compiling ESC[32mbuild/.conf_check_70a3d76b1100cfa99257f9574b0998de/test.cppESC[0m

['/mingw64/bin/g++', '-pipe', '-Wall', '-msse', '-msse2', '-mfpmath=sse', '-O2', '-fPIC', '-fno-strict-aliasing', '-march=x86-64', '-mtune=generic', '-O2', '-march=x86-64', '-mtune=generic', '-O2', '-I/usr/include/python2.7', '-D__STDC_CONSTANT_MACROS', '-DPYTHONDIR="/usr/local/lib/python2.7/site-packages"', '-DPYTHONARCHDIR="/usr/local/lib/python2.7/site-packages"', '-DNDEBUG', '-DNDEBUG', '-DNDEBUG', '../test.cpp', '-c', '-o/home/User/essentia/build/.conf_check_70a3d76b1100cfa99257f9574b0998de/testbuild/test.cpp.1.o', '-fPIC']
err: In file included from C:/msys64/usr/include/python2.7/Python.h:58:0,
                 from ../test.cpp:2:
C:/msys64/usr/include/python2.7/pyport.h:351:24: fatal error: sys/select.h: No such file or directory
 #include <sys/select.h>
                        ^
compilation terminated.

from /home/User/essentia/src/python: Test does not build: Traceback (most recent call last):
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Configure.py", line 327, in run_build
    bld.compile()
  File "/home/User/essentia/.waf-1.9.11-af9ceda667eab9a2b3fb893b34583f23/waflib/Build.py", line 186, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed with exit status 1 (run with -v to display more information)

Could not build a python embedded interpreter
from /home/User/essentia/src/python: The configuration failed
```

**Comment by ita1024** [comment]
Can you find "select.h" on your system? Where?

**Comment by ita1024** [comment]
This seems completely unrelated to waf.
