### ISSUE TITLE
Can't find python36.lib when building a Python 3 extention on Windows

### ISSUE THREAD

**Issue by dbogdanov** [waf-project/waf#1996]
I am using  Build Tools for Visual Studio 2017 to build a python3 extension with waf. 

I get "Unable to find vcvarsall.bat" message and  ```config.log``` complains that: 
```
out: LINK : fatal error LNK1181: cannot open input file 'python3.6.lib'
# try again with -L$prefix/libs, and pythonXY name rather than pythonX.Y (win32)
out: LINK : fatal error LNK1181: cannot open input file 'python3.6m.lib'
# try again with -L$prefix/libs, and pythonXY name rather than pythonX.Y (win32)
```

I have a file ```python36.lib``` but not ```python3.6.lib```

Detailed log below:
```
c:\Users\User\Dev\essentia>python waf configure --with-python
Setting top to                           : c:\Users\User\Dev\essentia
Setting out to                           : c:\Users\User\Dev\essentia\build
→ configuring the project in c:\Users\User\Dev\essentia
→ Building in release mode
Building on win32
Checking for 'msvc' (C++ compiler)       : C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\CL.exe
Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\CL.exe
Checking for program 'CL'                : C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\CL.exe
Checking for program 'CL'                : C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\CL.exe
Checking for program 'MT'                : C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\x64\MT.exe
Checking for program 'pkg-config'        : not found
Checking for program 'pkg-config'        : not found
Checking for program 'pkg-config'        : not found
Checking for program 'pkg-config'        : not found
Checking for program 'pkg-config'        : not found
Checking for program 'pkg-config'        : not found
Checking for program 'pkg-config'        : not found
Checking for program 'pkg-config'        : not found
Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\CL.exe
Checking for program 'python'            : C:\Users\User\AppData\Local\Programs\Python\Python36-32\python.exe
Checking for python version >= 2.7.0     : 3.6.2
→ Configuring for python3
python-config                            : not found
Checking for library python3.6 in $prefix/libs : not found
Checking for library python3.6m in $prefix/libs : not found
Checking for library python36 in $prefix/libs   : yes
Traceback (most recent call last):
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Scripting.py", line 122, in waf_entry_point
    run_commands()
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Scripting.py", line 183, in run_commands
    ctx=run_command(cmd_name)
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Scripting.py", line 174, in run_command
    ctx.execute()
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Context.py", line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Context.py", line 129, in recurse
    user_function(self)
  File "c:\Users\User\Dev\essentia\wscript", line 267, in configure
    ctx.recurse('src')
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Context.py", line 129, in recurse
    user_function(self)
  File "c:\Users\User\Dev\essentia\src\wscript", line 158, in configure
    ctx.recurse('python')
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Context.py", line 129, in recurse
    user_function(self)
  File "c:\Users\User\Dev\essentia\src\python\wscript", line 22, in configure
    ctx.check_python_headers()
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Configure.py", line 177, in fun
    return f(*k,**kw)
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Tools\python.py", line 288, in check_python_headers
    dist_compiler.initialize()
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\distutils\msvc9compiler.py", line 374, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Users\User\AppData\Local\Programs\Python\Python36-32\lib\distutils\msvc9compiler.py", line 262, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat
```

config.log:

```
Checking for python version >= 2.7.0
3.6.2
['C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\python.exe', '-c', "from distutils.sysconfig import get_config_var, get_python_lib\n\nprint(repr(get_config_var('prefix') or ''))\nprint(repr(get_config_var('SO') or ''))\nprint(repr(get_config_var('LDFLAGS') or ''))\nprint(repr(get_config_var('LIBDIR') or ''))\nprint(repr(get_config_var('LIBPL') or ''))\nprint(repr(get_config_var('INCLUDEPY') or ''))\nprint(repr(get_config_var('Py_ENABLE_SHARED') or ''))\nprint(repr(get_config_var('MACOSX_DEPLOYMENT_TARGET') or ''))\nprint(repr(get_config_var('LDSHARED') or ''))\nprint(repr(get_config_var('CFLAGS') or ''))\nprint(repr(get_config_var('LDVERSION') or ''))"]
out: 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32'
'.cp36-win32.pyd'
''
''
''
'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\include'
''
''
''
''
''

'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32'
'.cp36-win32.pyd'
''
''
''
'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\include'
''
''
''
''
''

Configuration returned from ['C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\python.exe']:
prefix = 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32'
SO = '.cp36-win32.pyd'
LDFLAGS = ''
LIBDIR = ''
LIBPL = ''
INCLUDEPY = 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\include'
Py_ENABLE_SHARED = ''
MACOSX_DEPLOYMENT_TARGET = ''
LDSHARED = ''
CFLAGS = ''
LDVERSION = ''

----------------------------------------
python-config
not found
find program=['C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\python.exe-config', 'python3.6-config', 'python-config-3.6', 'python3.6m-config'] paths=['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\MSBuild\\15.0\\bin\\Roslyn', 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\x64', 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.15063.0\\x64', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\\\MSBuild\\15.0\\bin', 'C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\Common7\\IDE\\', 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\Common7\\Tools\\', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\', 'C:\\Program Files\\dotnet\\', 'C:\\Program Files\\Git\\cmd', 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\', 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\', 'C:\\Users\\User\\AppData\\Local\\Microsoft\\WindowsApps', ''] var='PYTHON_CONFIG' -> None
from c:\Users\User\Dev\essentia\src\python: Could not find the program ['C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\python.exe-config', 'python3.6-config', 'python-config-3.6', 'python3.6m-config']


# try again with -L$prefix/libs, and pythonXY name rather than pythonX.Y (win32)

----------------------------------------------
Checking for library python3.6 in $prefix/libs
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32mbuild\conf_check_c6e299000591e7b600cde4518bc57a9f\test.cpp[0m

['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\CL.exe', '-W2', '-EHsc', '-O2', '/nologo', '/nologo', '/nologo', '/nologo', '/IC:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\include', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\ucrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\shared', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\um', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\winrt', '/D__STDC_CONSTANT_MACROS', '/DPYTHONDIR="C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\Lib\\site-packages"', '/DPYTHONARCHDIR="C:\\Users\\User\\AppData\\Local\\Temp\\Lib\\site-packages"', '..\\test.cpp', '/FC', '/c', '/Foc:\\Users\\User\\Dev\\essentia\\build\\conf_check_c6e299000591e7b600cde4518bc57a9f\\testbuild\\test.cpp.1.o']
out: test.cpp

[2/2] Linking [33mbuild\conf_check_c6e299000591e7b600cde4518bc57a9f\testbuild\testprog.exe[0m

['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\LINK.exe', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', 'test.cpp.1.o', '/OUT:c:\\Users\\User\\Dev\\essentia\\build\\conf_check_c6e299000591e7b600cde4518bc57a9f\\testbuild\\testprog.exe', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.15063.0\\', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.15063.0\\', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.15063.0\\', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.15063.0\\', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', '/LIBPATH:C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\libs', 'python3.6.lib']
out: LINK : fatal error LNK1181: cannot open input file 'python3.6.lib'

from c:\Users\User\Dev\essentia\src\python: Test does not build: Traceback (most recent call last):
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Configure.py", line 327, in run_build
    bld.compile()
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Build.py", line 186, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 1181 (run with -v to display more information)

not found
from c:\Users\User\Dev\essentia\src\python: The configuration failed


# try again with -L$prefix/libs, and pythonXY name rather than pythonX.Y (win32)

-----------------------------------------------
Checking for library python3.6m in $prefix/libs
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32mbuild\conf_check_cc293ce9e8d48a1c01edae522c7d081c\test.cpp[0m

['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\CL.exe', '-W2', '-EHsc', '-O2', '/nologo', '/nologo', '/nologo', '/nologo', '/IC:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\include', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\ucrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\shared', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\um', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\winrt', '/D__STDC_CONSTANT_MACROS', '/DPYTHONDIR="C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\Lib\\site-packages"', '/DPYTHONARCHDIR="C:\\Users\\User\\AppData\\Local\\Temp\\Lib\\site-packages"', '..\\test.cpp', '/FC', '/c', '/Foc:\\Users\\User\\Dev\\essentia\\build\\conf_check_cc293ce9e8d48a1c01edae522c7d081c\\testbuild\\test.cpp.1.o']
out: test.cpp

[2/2] Linking [33mbuild\conf_check_cc293ce9e8d48a1c01edae522c7d081c\testbuild\testprog.exe[0m

['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\LINK.exe', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', 'test.cpp.1.o', '/OUT:c:\\Users\\User\\Dev\\essentia\\build\\conf_check_cc293ce9e8d48a1c01edae522c7d081c\\testbuild\\testprog.exe', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.15063.0\\', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.15063.0\\', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.15063.0\\', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.15063.0\\', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', '/LIBPATH:C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\libs', 'python3.6m.lib']
out: LINK : fatal error LNK1181: cannot open input file 'python3.6m.lib'

from c:\Users\User\Dev\essentia\src\python: Test does not build: Traceback (most recent call last):
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Configure.py", line 327, in run_build
    bld.compile()
  File "c:\Users\User\Dev\essentia\waf3-1.9.12-46ae1733752575b7ea2378b1eca4e1ae\waflib\Build.py", line 186, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 1181 (run with -v to display more information)

not found
from c:\Users\User\Dev\essentia\src\python: The configuration failed


# try again with -L$prefix/libs, and pythonXY name rather than pythonX.Y (win32)

-----------------------------------------------
Checking for library python36 in $prefix/libs
==>

int main(int argc, char **argv) {
	(void)argc; (void)argv;
	return 0;
}

<==
[1/2] Compiling [32mbuild\conf_check_379b7519be6af62650e64577f0185823\test.cpp[0m

['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\CL.exe', '-W2', '-EHsc', '-O2', '/nologo', '/nologo', '/nologo', '/nologo', '/IC:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\include', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\ucrt', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\shared', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\um', '/IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.15063.0\\winrt', '/D__STDC_CONSTANT_MACROS', '/DPYTHONDIR="C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\Lib\\site-packages"', '/DPYTHONARCHDIR="C:\\Users\\User\\AppData\\Local\\Temp\\Lib\\site-packages"', '..\\test.cpp', '/FC', '/c', '/Foc:\\Users\\User\\Dev\\essentia\\build\\conf_check_379b7519be6af62650e64577f0185823\\testbuild\\test.cpp.1.o']
out: test.cpp

[2/2] Linking [33mbuild\conf_check_379b7519be6af62650e64577f0185823\testbuild\testprog.exe[0m

['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\bin\\HostX64\\x64\\LINK.exe', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', '/nologo', '/MANIFEST', 'test.cpp.1.o', '/OUT:c:\\Users\\User\\Dev\\essentia\\build\\conf_check_379b7519be6af62650e64577f0185823\\testbuild\\testprog.exe', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\ucrt\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\lib\\10.0.15063.0\\um\\x64', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.15063.0\\', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.15063.0\\', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', '/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.10.25017\\lib\\x64', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.15063.0\\', '/LIBPATH:C:\\Program Files (x86)\\Windows Kits\\10\\References\\10.0.15063.0\\', '/LIBPATH:C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319', '/LIBPATH:C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\libs', 'python36.lib']
['C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.15063.0\\x64\\MT.exe', '/nologo', '-manifest', 'c:\\Users\\User\\Dev\\essentia\\build\\conf_check_379b7519be6af62650e64577f0185823\\testbuild\\testprog.exe.manifest', '-outputresource:c:\\Users\\User\\Dev\\essentia\\build\\conf_check_379b7519be6af62650e64577f0185823\\testbuild\\testprog.exe;1']
yes
Include path for Python extensions (found via distutils module): 'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python36-32\\include'
```

**Comment by ita1024** [comment]
It looks like there is a distutils error, so i am not sure what we can do.

**Comment by dbogdanov** [comment]
I've solved this issue by monkey patching ``distutils.msvc9compiler`` and ``distutils.msvccompiler`` with ```import setuptools```. 

This is a common problem, but it seems that distutils itself won't be fixed anytime soon. Therefore, I suppose that more waf projects may get into this problem.

**Comment by ita1024** [comment]
Closing this case because there is no further action to take on this matter.
