### ISSUE TITLE
valueerror: could not convert string to float

### ISSUE THREAD

**Issue by xoviat** [waf-project/waf#2002]
https://ci.appveyor.com/project/matysek/pyinstaller/build/2308/job/tb4to3pk2afqf18w

```
python waf all --target-arch=%PYTHON_ARCH%bit
'all' finished successfully (0.000s)
'distclean' finished successfully (0.000s)
Setting top to                           : C:\projects\pyinstaller\bootloader 
Setting out to                           : C:\projects\pyinstaller\bootloader\build 
Checking for 'msvc' (C compiler)         : Traceback (most recent call last):
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Scripting.py", line 120, in waf_entry_point
    run_commands()
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Scripting.py", line 181, in run_commands
    ctx=run_command(cmd_name)
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Scripting.py", line 172, in run_command
    ctx.execute()
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Configure.py", line 85, in execute
    super(ConfigurationContext,self).execute()
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Context.py", line 88, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Context.py", line 129, in recurse
    user_function(self)
  File "C:\projects\pyinstaller\bootloader\wscript", line 402, in configure
    ctx.load('compiler_c')  # Any available C compiler.
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Configure.py", line 153, in load
    if type(func)is type(Utils.readf):func(self)
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Tools\compiler_c.py", line 23, in configure
    conf.load(compiler)
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Configure.py", line 153, in load
    if type(func)is type(Utils.readf):func(self)
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Tools\msvc.py", line 496, in configure
    conf.autodetect(True)
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Configure.py", line 174, in fun
    return f(*k,**kw)
  File "C:\projects\pyinstaller\bootloader\waf3-1.9.7-748e4d61d5a6939389e8e9761f0e716b\waflib\Tools\msvc.py", line 522, in autodetect
    v.MSVC_VERSION=float(version)
ValueError: could not convert string to float: '9.0Exp'
```

**Comment by ita1024** [comment]
Update your copy.

**Comment by xoviat** [comment]
@htgoebel

**Comment by htgoebel** [comment]
@xoviat Done.

**Comment by xoviat** [comment]
The issue appears to be resolved.
