### ISSUE TITLE
Error in waflib syms?

### ISSUE THREAD

**Issue by 7heW4yne** [waf-project/waf#2007]
I started [my own fork of the "aubio" project](https://github.com/7heW4yne/aubio) to enhance its build process in order to create DEF files for the DLL.
In my fork I added the waf-file and the complete waflib directory of waf  version 1.9.13 (just to do some tests - later it should be download and extract the waflib automatically).

But when I try to run the build I get:

> Build failed
Traceback (most recent call last):
  File "/aubio/waflib/Task.py", line 294, in process
    ret = self.run()
  File "/aubio/waflib/extras/syms.py", line 52, in run
    self.outputs[0].write('{ global:\n' + ';\n'.join(lsyms) + ";\nlocal: *; };\n")
TypeError: sequence item 0: expected string, tuple found

I tested the syms example from the playground folder and compared the created sym-files with the files from my aubio fork.

In the playground-example the sym file looks like:

> ['mylib_aa']

In my aubio fork it looks like:

> [('cvec_copy', 'cvec'), ('cvec_logmag', 'cvec'), ('cvec_norm_get_data', 'cvec'), ('cvec_norm_get_sample', 'cvec'), ('cvec_norm_ones', 'cvec'), ('cvec_norm_set_all', 'cvec'), ('cvec_norm_set_sample', 'cvec'), ('cvec_norm_zeros', 'cvec'), ('cvec_phas_get_data', 'cvec'), ('cvec_phas_get_sample', 'cvec'), ('cvec_phas_ones', 'cvec'), ('cvec_phas_set_all', 'cvec'), ('cvec_phas_set_sample', 'cvec'), ('cvec_phas_zeros', 'cvec'), ('cvec_print', 'cvec'), ('cvec_zeros', 'cvec'), ('del_cvec', 'del'), ('new_cvec', 'new')]

My `export_symbols_regex` is: `(new|del|aubio|fvec|fmat|cvec|lvec)_.*`
I think this causes the "tuple" layout of the sym files. **BUT** I don't know why the `syms.py` cannot handle that.

As far as I can see, this problem can be fixed by adding 1 line to [syms.py after line 47](https://github.com/waf-project/waf/blob/master/waflib/extras/syms.py#L47):

> lsyms = [x[0] for x in lsyms]

But I don't know anything about the consequences, because I'm not a waf expert.

Is that an error in waf, in the syms.py or is there something wrong with my `export_symbols_regex`?

**Comment by ita1024** [comment]
The syms example was recently extended to handle global variables, so the regexp format has changed. If in doubt, try one version back?

**Comment by 7heW4yne** [comment]
Thanks for your answer.

But I don't understand what the handling of global variable has to do regular expression's. But I will try.

I think you mean the new waf 2 RC versions. Am I right?

**Comment by ita1024** [comment]
Please read the git log for syms.py.
