### ISSUE TITLE
Accidental cross-context "includes" list sharing

### ISSUE THREAD

**Issue by daniel-brosche** [waf-project/waf#2035]
I have found an issue and I was able to reproduce them by extending the playground/use example.

https://github.com/daniel-brosche/waf/commit/08f560e465158e82a0ada08b9e05897f606cdb7a

When I build this example with: 
```
waf-light configure build install --destdir=/tmp/
```

I get this error:
```
Traceback (most recent call last):
  File "/home/brosche/Dev/waf_fork_github/waflib/Scripting.py", line 157, in waf_entry_point
    run_commands()
  File "/home/brosche/Dev/waf_fork_github/waflib/Scripting.py", line 242, in run_commands
    ctx = run_command(cmd_name)
  File "/home/brosche/Dev/waf_fork_github/waflib/Scripting.py", line 226, in run_command
    ctx.execute()
  File "/home/brosche/Dev/waf_fork_github/waflib/Scripting.py", line 564, in execute
    return execute_method(self)
  File "/home/brosche/Dev/waf_fork_github/waflib/Build.py", line 231, in execute
    self.execute_build()
  File "/home/brosche/Dev/waf_fork_github/waflib/Build.py", line 251, in execute_build
    self.compile()
  File "/home/brosche/Dev/waf_fork_github/waflib/Build.py", line 345, in compile
    self.producer.start()
  File "/home/brosche/Dev/waf_fork_github/waflib/Runner.py", line 398, in start
    self.refill_task_list()
  File "/home/brosche/Dev/waf_fork_github/waflib/Runner.py", line 244, in refill_task_list
    tasks = next(self.biter)
  File "/home/brosche/Dev/waf_fork_github/waflib/Build.py", line 797, in get_build_iterator
    self.post_group()
  File "/home/brosche/Dev/waf_fork_github/waflib/Build.py", line 763, in post_group
    tgpost(tg)
  File "/home/brosche/Dev/waf_fork_github/waflib/Build.py", line 741, in tgpost
    f()
  File "/home/brosche/Dev/waf_fork_github/waflib/TaskGen.py", line 239, in post
    v()
  File "/home/brosche/Dev/waf_fork_github/waflib/Tools/ccroot.py", line 124, in apply_incpaths
    self.env.INCPATHS = [x.path_from(cwd) for x in lst]
  File "/home/brosche/Dev/waf_fork_github/waflib/Node.py", line 468, in path_from
    if c1.parent:
```
However when I use the command seperately like:

```
waf-light configure build
```
and then:

```
../../waf-light configure install --destdir=/tmp/
```

No error occurs.

After some investigation I found that the exports_include configuration of the lib subproject does somehow provoke this issue.

When I comment the export_includes part in playground/use/objects/lib/wscript:
```
    bld.shlib(
        #features='selective_install',
        target='lib',
        source='lib.c',
        includes=INCLUDES,
       # export_includes=INCLUDES,
        install_path=bld.env.LIBDIR,
    )
```
and include the header directly in playground/use/objects/libex/wscript no error occurs.

**Comment by ita1024** [comment]
Could you use `includes=list(INCLUDES)` in the meantime?

**Comment by daniel-brosche** [comment]
Sure, for the meantime... 

I also noticed that just calling

```
waf-light distclean configure install --destdir=/tmp/
```
works without problems which basically does an implicit build. Strange isn't it...
Why does ` includes=list(INCLUDES) ` does solve the problem? INCLUDES is basically a list. Because of a deep copy of the argument?

Btw.: I currently porting are large bunch of our embedded source to waf with complex multiproject scenarios which caused this issue. In this scope I preparing a template for our projects that are probably worth to share for other developers.

**Comment by ita1024** [comment]
This is also present in waf 1.9.

**Comment by daniel-brosche** [comment]
Last commit does not solve the issue on my side.

**Comment by ita1024** [comment]
No, it will not.

**Comment by ita1024** [comment]
Update to 113e42e485a1b9d91a94355e97b07966cb1023f1

**Comment by daniel-brosche** [comment]
Great :+1:

**Comment by ita1024** [comment]
I accidentally closed instead of just commenting, but i imagine that you updated your copy.
