### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by drahnr** [waf-project/waf#2159]
`-rw-rw-r--. 1 bernhard bernhard unconfined_u:object_r:user_home_t:s0 149 11. Apr 23:22 ./src/yadayada`

`-rwxr-xr-x. 1 bernhard bernhard unconfined_u:object_r:user_home_t:s0 100998  3. Mai 21:44 ./waf`

```
Build failed
Traceback (most recent call last):
  File "/home/bernhard/Projects/Bewerbung/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Task.py", line 110, in process
    ret=self.run()
  File "/home/bernhard/Projects/Bewerbung/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Tools/tex.py", line 200, in run
    self.call_latex()
  File "/home/bernhard/Projects/Bewerbung/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Tools/tex.py", line 230, in call_latex
    self.check_status('error when calling latex',self.texfun())
  File "<string>", line 16, in f
  File "/home/bernhard/Projects/Bewerbung/.waf3-1.8.20-c859ca7dc3693011756f4edf45c36626/waflib/Tools/tex.py", line 52, in exec_command
    return Utils.subprocess.Popen(cmd,**kw).wait()
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '
```

`I double checked and /var/log/audit/audit.log does not contain any issues.

```
#!/usr/bin/env python3

top = '.'
out = 'build'

def options(opt):
	opt.load('tex')

def configure(cfg):
	cfg.load('tex')
	if not cfg.env.XELATEX:
		cfg.fatal('could not find the program xelatex')


def build(bld):
	bld.load('tex')
	bld(features = 'tex',
		type = 'pdflatex',
		outs = 'pdf',
		source = 'src/yadayada.tex',
		)


from waflib.Context import Context

def view_fun(ctx):
	import subprocess
	subprocess.call("xdg-open "+out+"/glue/yadayada.pdf > /dev/null", stdout=None, stderr=None, shell=True)

class view(Context):
	"""View it in your favorite pdf viewer"""
	cmd = 'view'
	fun = 'view_fun'
```

**Comment by drahnr** [comment]
Well, its late, so in this case the check wants XELATEX where the actual command wants PDFLATEX
